CREATE DATABASE IF NOT EXISTS company_db CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS ta_cust (
	cust_uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	stus_cod VARCHAR(1) NOT NULL,
	name VARCHAR(50),
	email VARCHAR(100),
	phone VARCHAR(20),
	dob DATE,
	crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lst_upd_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	upd_cntr INT NOT NULL DEFAULT 0,
	INDEX idx_cust_uid (cust_uid),
	FOREIGN KEY fk_stus_cod(stus_cod)
		REFERENCES ta_cust_stus(stus_cod)
);

CREATE TABLE IF NOT EXISTS ta_cust_note (
	cust_note_uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cust_uid INT NOT NULL,
	note VARCHAR(500) NOT NULL,
	crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lst_upd_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	upd_cntr INT NOT NULL DEFAULT 0,
	INDEX idx_cust_note_uid (cust_note_uid),
	INDEX idx_cust_uid (cust_uid),
	FOREIGN KEY fk_cust_uid(cust_uid)
		REFERENCES ta_cust(cust_uid)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ta_cust_stus (
	stus_cod VARCHAR(1) NOT NULL PRIMARY KEY,
	stus VARCHAR(20) NOT NULL,
	crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lst_upd_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	upd_cntr INT NOT NULL DEFAULT 0	
);